version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/teste-cotabox
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
